poller_root/pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

poller_root/poller/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('polls/', include('polls.urls')),
]

poller_root/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
	path('', views.index, name='index'),
	path('<int:survey_id>/', views.survey, name='survey'),
	path('<int:question_id>/vote/', views.vote, name='vote'),
	path('<int:question_id>/results/', views.results, name='results'),
]

poller_root/polls/models.py
from django.db import models
from django.urls import reverse


class Survey(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')

    class Meta:
        verbose_name = 'Опрос'
        verbose_name_plural = 'Опросы'

    # def get_absolute_url(self):
    #     return reverse("polls:survey", kwargs={"id": self.id})

    def __str__(self):
        return self.name


# https://habr.com/ru/articles/5959/
class Question(models.Model):
    question_text = models.CharField(max_length=250, verbose_name='Вопрос')
    pub_date = models.DateTimeField(verbose_name='Дата публикации')
    survey = models.ForeignKey(
        Survey,
        on_delete=models.CASCADE,
        related_name='questions')
    code = models.CharField(max_length=15, unique=True, null=False, blank=False)
    previous_question = models.ForeignKey(
        'self',
        verbose_name='Прошлый вопрос',
        related_name='children',
        on_delete=models.SET_NULL,
        blank=True,
        null=True)
    path = models.CharField(max_length=255, null=False, editable=False)

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'

    # https://pyformat.info/
    def __str__(self):
        return "%s%s" % ('------'[:self.path.count('/', 2)-1], self.question_text)

    def save(self):
        if self.previous_question:
            self.path = f'{self.previous_question.path}{self.code}/'
        else:
            self.path = f'/{self.code}/'
            super(type(self), self).save()
        for a in Question.objects.filter(previous_question=self.id):
            a.save()


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100, verbose_name='Ответ')
    votes = models.PositiveIntegerField(default=0, verbose_name='Количество голосов')

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

    def __str__(self):
        return self.choice_text

poller_root/pages/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'pages/index.html')

poller_root/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse

from .models import Choice, Question, Survey


# Get questions and display them
def index(request):
    surveys = Survey.objects.all()
    context = {'surveys': surveys}
    return render(request, 'poller/index.html', context)


# Show specific question and choices
# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Страницы с таким вопросом не существует :(")
#     return render(request, 'poller/detail.html', {'question': question})

def survey(request, survey_id):
    survey = Survey.objects.get(pk=survey_id)
    questions = Question.objects.filter(survey_id=survey_id)
    for i in questions:
        print(f'Вопрос:{str(i)}')
    return render(
        request,
        'poller/survey.html',
        {
            'survey': survey,
            'questions': questions
        }
    )


# Get question and display results
def results(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    return render(request, 'poller/results.html', {'question': question})


# Vote for a question choice
def vote(request, question_id):
    print(f'request.POST = {request.POST}')
    question = Question.questions.get(id=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'poller/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))


# # Vote for a question choice
# def vote(request, question_id):
#     # print(request.POST['choice'])
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choice_set.get(pk=request.POST['choice'])
#     except (KeyError, Choice.DoesNotExist):
#         # Redisplay the question voting form.
#         return render(request, 'poller/detail.html', {
#             'question': question,
#             'error_message': "You didn't select a choice.",
#         })
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse('polls:results', args =(question.id, )))

poller_root/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
		integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<title>Опросник
        {% block title %}
        {% endblock %}
    </title>
</head>

<body>
	<!--NavBar-->
	{% include 'partials/_navbar.html'%}
	<div class="container">
		<div class="row">
			<div class=".col-md-6 m-auto">
				{% block content %}
                {% endblock%}
			</div>
		</div>
	</div>
</body>

</html>

poller_root/templates/pages/index.html
{% extends 'base.html' %}
{% block content %}

<div class="card text-center">
	<div class="card-body">
		<h1>Добро пожаловать на опрос!</h1>
		<p>Это быстрое тестовое задание на Django</p>
		<a class="btn btn-dark" href="{% url 'polls:index' %}">
			Показать вопросы</a>
	</div>
</div>
{% endblock %}

poller_root/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
    <div class="container">
        <a class="navbar-brand" href="/" >Опросникъ</a>
    </div>
</nav>

poller_root/templates/poller/index.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center mb-3">Вопросы</h1>

{% if surveys %}
	{% for survey in surveys %}
		<div class="card-mb-3">
			<div class="card-body">
				<p class="lead">{{ survey.name }}</p>
				<a href="{% url 'polls:survey' survey.id %}" class="btn btn-primary btn-sm">Пройти опрос</a>
			</div>
		</div>
	{% endfor %}
{% else %}
	<p>Нет доступных вопросов</p>
{% endif %}

{% endblock %}

poller_root/templates/poller/results.html
{% extends 'base.html' %}
{% block content %}
{% load plural_ru %}
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>

<ul class="list-group mb-5">
	{% for choice in question.choice_set.all %}
	<li class="list-group-item">
		{{ choice.choice_text }} <span class="badge badge-success float-right"> {{ choice.votes}}
			{{ choice.votes |ru_plural }}
			</span> 
	</li>
	{% endfor %}
</ul>

<a class="btn btn-secondary" href="{% url 'polls:index' %}">К вопросам</a>
<a class="btn btn-dark" href="{% url 'polls:detail' question.id %}">Ответить еще раз</a>
{% endblock %}

poller_root/templates/poller/survey.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'polls:index' %}">Назад</a>
<h1 class="text-center mb-3">{{ survey.name }}</h1>

{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

{% for question in questions %}
	<p> <i> {{ question.question_text }} </i> </p>
	<form action="{% url 'polls:vote' question.id %}" method="post">
		{% csrf_token %}
		{% for choice in question.choice_set.all %}
			<div class="form-check">
				<input type="radio" name="choice" class="form-check-input" id="choice{{ forloop.counter }}"
					value="{{ choice.id }}" />
				<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
			</div>
		{% endfor %}
		<input type="submit" value="Ответить" class="btn btn-success btn-lg btn-block mt-4" />
		<br>
	</form>
{% endfor %}
{% endblock %}